config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands, only:[:index, :create, :new, :edit, :show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

    # F - ::find_by_credentials
    # I - #is_password?
    # G - ::generate_session_token
    # V - validates :password
    # A - attr_reader :password
    # P - #password=
    # E - #ensure_session_token
    # R - #reset_session_token!

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  #celll

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def login!(user)
    session[session_token] = user.reset_session_token!
  end

  def logout!
    session[:session_token] = new_session_url
    @current_user = new_session_url
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def create
    band = Band.new(name)
    if band.save
      render :new
    else
      render json: band.errors.full_message
    end
  end

  def new
    render :new
  end

  def edit
    
    render :edit
  end

  def show
    band = Band.find(params[:id])
    render :show
  end

  def update
    band = Band.find(params[:id])
    if band.update(name)
      render :edit
    else
       render json: band.errors.full_message 
    end
  end

  def destroy
    band = Band.find(params[:id])   
    if band 
      band.destroy
      redirect_to band_url
    else
      render json: 'band not found', status:404
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = user.find_by_credentials(params[user :email][user :password])
    if user
      session[:session_token] = @user.reset_session_token!
      redirect_to user_show
    else
      flash.new[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    session[:session_toekn] = nil
    current_user.reset_session_token!
    redirect_to users_show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new
    if @user.save
      session[:session_token] = @user.reset_session_token!
      redirect_to users_url
    else
      flash.new[:errors] = @user.full_message
      render :new
    end
  end

  def show
    user = Users.find
    render :show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<h1>Edit a Band</h1>
  <form action="<%= users_url %>" method="POST">
  <label for="name">Band Name</label>
  <input id="name" type="text" name="user[name]" value="">
  <input type="submit" value="Submit">
</form>

app/views/bands/index.html.erb
<h1>BAND LIST</h1>

<ul>
  <% @bands.each do |band| %>
    <li>
      <%= band.name %>
      <a href="<%= bands_url(name) %>">show band</a>
    </li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>Add a Band</h1>
  <form action="<%= users_url %>" method="POST">
  <label for="name">Band Name</label>
  <input id="name" type="text" name="user[name]" value="">
  <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">  
  
  </head>

  <body>
    <header> Music App </header> <br>
      <% if logged_in? %>
        <form action="<%= users_url %>" method="POST">
        <a href="<% users_url %>">Sign Out></a>
        </form>
        <% else %>
        <form action="<%= session_url %>" method="POST">
        <a href="<% users_url %>">Log In></a>
        </form>
      <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
  <html>
  
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="">

  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]" value="">

  <input type="submit" value="Sign Up">
</form>

</html>

  